export default [
    {word: 'airplane',          image: 'images/airplane.jpg',       bg: '#7ea4e5', tags: ['activities']},
    {word: 'apple',             image: 'images/apple.jpg',          bg: '#ffffff', tags: ['food']},
    {word: 'apple sauce',       image: 'images/apple_sauce.png',    bg: '#ffffff', tags: ['food']},
    {word: 'arm',               image: 'images/arm.jpg',            bg: '#ffffff', tags: ['body']},
    {word: 'baby',              image: 'images/baby.jpg',           bg: '#ffffff', tags: ['activities']},
    {word: 'ball',              image: 'images/ball.jpg',           bg: '#ffffff', tags: ['activities']},
    {word: 'banana',            image: 'images/banana.jpg',         bg: '#9cc2c5', tags: ['food']},
    {word: 'bath',              image: 'images/bath.jpg',           bg: '#c1aa8b', tags: ['activities']},
    {word: 'bed',               image: 'images/bed.jpg',            bg: '#ffffff', tags: ['household']},
    {word: 'belly button',      image: 'images/belly_button.jpg',   bg: '#ffffff', tags: ['body']},
    //{word: 'black',           image: 'images/black.jpg',          bg: '#000000', tags: ['colors']},
    {word: 'blanket',           image: 'images/blanket.jpg',        bg: '#e2e2e4', tags: ['household']},
    //{word: 'blue',            image: 'images/blue.jpg',           bg: '#000000', tags: ['colors']},
    {word: 'boat',              image: 'images/boat.jpg',           bg: '#afacb2', tags: ['activities']},
    {word: 'book',              image: 'images/book.webp',          bg: '#606060', tags: ['activities']},
    {word: 'bowl',              image: 'images/bowl.jpg',           bg: '#ffffff', tags: ['eating']},
    {word: 'bubble',            image: 'images/bubble.jpg',         bg: '#000000', tags: ['activities']},
    {word: 'bus',               image: 'images/bus.jpg',            bg: '#ffffff', tags: ['activities']},
    {word: 'car',               image: 'images/car.jpg',            bg: '#ffffff', tags: ['activities']},
    {word: 'chair',             image: 'images/chair.jpg',          bg: '#ffffff', tags: ['household']},
    {word: 'cheek',             image: 'images/cheek.jpg',          bg: '#ffffff', tags: ['body']},
    {word: 'chin',              image: 'images/chin.jpg',           bg: '#ffffff', tags: ['body']},
    {word: 'circle',            image: 'images/circle.jpg',         bg: '#000000', tags: ['shapes']},
    {word: 'clock',             image: 'images/clock.jpg',          bg: '#ffffff', tags: ['household']},
    {word: 'couch',             image: 'images/couch.jpg',          bg: '#ffffff', tags: ['household']},
    {word: 'cow',               image: 'images/cow.jpg',            bg: '#7babff', tags: ['animals']},
    {word: 'cup',               image: 'images/cup.jpg',            bg: '#ffffff', tags: ['eating', 'household']},
    {word: 'dog',               image: 'images/dog.jpg',            bg: '#ffffff', tags: ['animals']},
    {word: 'door',              image: 'images/door.jpg',           bg: '#ffffff', tags: ['household']},
    //{word: 'dryer',           image: 'images/dryer.jpg',          bg: '#000000', tags: ['household']},
    {word: 'duck',              image: 'images/duck.jpg',           bg: '#ffffff', tags: ['animals']},
    {word: 'ear',               image: 'images/ear.webp',           bg: '#000000', tags: ['body']},
    {word: 'eye',               image: 'images/eye.jpg',            bg: '#f9b593', tags: ['body']},
    {word: 'eyebrow',           image: 'images/eyebrow.jpg',        bg: '#edbb96', tags: ['body']},
    {word: 'finger',            image: 'images/finger.jpeg',        bg: '#ffffff', tags: ['body']},
    {word: 'fish',              image: 'images/fish.png',           bg: '#ffffff', tags: ['animals']},
    {word: 'flower',            image: 'images/flower.jpg',         bg: '#405423', tags: ['activities']},
    {word: 'foot',              image: 'images/foot.jpg',           bg: '#ffffff', tags: ['body']},
    {word: 'fork',              image: 'images/fork.jpg',           bg: '#ffffff', tags: ['eating']},
    {word: 'fridge',            image: 'images/fridge.jpg',         bg: '#000000', tags: ['eating', 'household']},
    {word: 'go',                image: 'images/go.png',             bg: '#000000', tags: ['activities']},
    //{word: 'goodbye',         image: 'images/goodbye.jpg',        bg: '#000000', tags: ['activities']},
    {word: 'grass',             image: 'images/grass.jpg',          bg: '#305312', tags: ['household']},
    //{word: 'green',           image: 'images/green.jpg',          bg: '#000000', tags: ['colors']},
    {word: 'hair',              image: 'images/hair.jpg',           bg: '#8d9da0', tags: ['body']},
    {word: 'hand',              image: 'images/hand.jpg',           bg: '#ffffff', tags: ['body']},
    //{word: 'happy',           image: 'images/happy.jpg',          bg: '#000000', tags: ['activities']},
    //{word: 'head',            image: 'images/head.jpg',           bg: '#000000', tags: ['body']},
    //{word: 'hello',           image: 'images/hello.jpg',          bg: '#000000', tags: ['activities']},
    {word: 'house',             image: 'images/house.webp',         bg: '#c1b9d9', tags: ['household']},
    {word: 'knife',             image: 'images/knife.jpg',          bg: '#ffffff', tags: ['eating']},
    {word: 'leg',               image: 'images/leg.jpg',            bg: '#ffffff', tags: ['body']},
    {word: 'light',             image: 'images/light.jpg',          bg: '#a7a7a9', tags: ['household']},
    //{word: 'line',            image: 'images/line.jpg',           bg: '#000000', tags: ['shapes']},
    {word: 'microwave',         image: 'images/microwave.jpeg',     bg: '#ffffff', tags: ['eating']},
    {word: 'milk',              image: 'images/milk.jpg',           bg: '#bebebe', tags: ['food']},
    {word: 'mirror',            image: 'images/mirror.jpg',         bg: '#808080', tags: ['household']},
    {word: 'moon',              image: 'images/moon.jpg',           bg: '#303c5c', tags: ['activities']},
    {word: 'mouse',             image: 'images/mouse.jpg',          bg: '#ffffff', tags: ['animals']},
    {word: 'mouth',             image: 'images/mouth.jpg',          bg: '#f6d1be', tags: ['body']},
    {word: 'nose',              image: 'images/nose.webp',          bg: '#fedfd0', tags: ['body']},
    //{word: 'orange',          image: 'images/orange.jpg',         bg: '#000000', tags: ['colors']},
    //{word: 'oval',            image: 'images/oval.jpg',           bg: '#000000', tags: ['shapes']},
    {word: 'pacifier',          image: 'images/pacifier.jpg',       bg: '#ffffff', tags: ['household']},
    {word: 'pants',             image: 'images/pants.jpg',          bg: '#ffffff', tags: ['body']},
    {word: 'pear',              image: 'images/pear.jpg',           bg: '#ffffff', tags: ['food']},
    {word: 'penguin',           image: 'images/penguin.jpg',        bg: '#dae7f2', tags: ['animals']},
    {word: 'pepper',            image: 'images/pepper.jpg',         bg: '#ffffff', tags: ['food']},
    {word: 'pillow',            image: 'images/pillow.jpg',         bg: '#ffffff', tags: ['household']},
    {word: 'plate',             image: 'images/plate.jpg',          bg: '#ffffff', tags: ['eating', 'household']},
    {word: 'potty',             image: 'images/potty.jpg',          bg: '#ffffff', tags: ['household']},
    //{word: 'purple',          image: 'images/purple.jpg',         bg: '#000000', tags: ['colors']},
    {word: 'quail',             image: 'images/quail.jpg',          bg: '#9b8a78', tags: ['animals']},
    //{word: 'red',             image: 'images/red.jpg',            bg: '#000000', tags: ['colors']},
    //{word: 'rectangle',       image: 'images/rectangle.jpg',      bg: '#000000', tags: ['shapes']},
    //{word: 'sad',             image: 'images/sad.jpg',            bg: '#000000', tags: ['activities']},
    {word: 'sheep',             image: 'images/sheep.jpg',          bg: '#204020', tags: ['animals']},
    {word: 'shirt',             image: 'images/shirt.jpg',          bg: '#000000', tags: ['body']},
    {word: 'shoe',              image: 'images/shoe.jpg',           bg: '#ffffff', tags: ['body']},
    {word: 'shoulder',          image: 'images/shoulder.jpg',       bg: '#ffffff', tags: ['body']},
    {word: 'shower',            image: 'images/shower.jpg',         bg: '#919fb2', tags: ['household']},
    {word: 'sink',              image: 'images/sink.jpg',           bg: '#666c7a', tags: ['household']},
    {word: 'sit',               image: 'images/sit.jpeg',           bg: '#ffffff', tags: ['activities']},
    {word: 'sky',               image: 'images/sky.jpg',            bg: '#01599d', tags: ['activities']},
    {word: 'smoke detector',    image: 'images/smoke_detector.jpg', bg: '#d5d7cc', tags: ['household']},
    {word: 'spoon',             image: 'images/spoon.jpg',          bg: '#ffffff', tags: ['eating', 'household']},
    {word: 'square',            image: 'images/square.png',         bg: '#ffffff', tags: ['shapes']},
    //{word: 'stand up',        image: 'images/stand_up.jpg',       bg: '#000000', tags: ['activities']},
    {word: 'stop',              image: 'images/stop.jpg',           bg: '#ffffff', tags: ['activities']},
    {word: 'sun',               image: 'images/sun.jpeg',           bg: '#d28002', tags: ['activities']},
    {word: 'table',             image: 'images/table.jpg',          bg: '#ffffff', tags: ['eating', 'household']},
    {word: 'toe',               image: 'images/toe.jpg',            bg: '#354f6d', tags: ['body']},
    {word: 'tomato',            image: 'images/tomato.jpg',         bg: '#ffffff', tags: ['food']},
    {word: 'train',             image: 'images/train.jpg',          bg: '#d0e1f1', tags: ['activities']},
    {word: 'tree',              image: 'images/tree.jpg',           bg: '#f7f7f7', tags: ['activities']},
    {word: 'triangle',          image: 'images/triangle.png',       bg: '#000000', tags: ['shapes']},
    {word: 'truck',             image: 'images/truck.jpeg',         bg: '#606060', tags: ['activities']},
    //{word: 'washer',          image: 'images/washer.jpg',         bg: '#000000', tags: ['household']},
    {word: 'water',             image: 'images/water.jpg',          bg: '#1463a1', tags: ['activities']},
    {word: 'wave',              image: 'images/wave.jpg',           bg: '#d0d0d8', tags: ['activities']},
    //{word: 'white',           image: 'images/white.jpg',          bg: '#000000', tags: ['colors']},
    //{word: 'yellow',          image: 'images/yellow.jpg',         bg: '#000000', tags: ['colors']},
  ];